name: Main build
description: Sets up JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
  dependency-graph:
    required: false
    description: 'see https://github.com/gradle/gradle-build-action#enable-dependency-graph-generation-for-a-workflow'
    default: disabled
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-test-jdk
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
        dependency-graph: ${{ inputs.dependency-graph }}
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test Distribution trace files (${{ github.job }})
        path: '**/build/test-results/*/trace.json'
