name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
